# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  cypress: cypress-io/cypress@1.28.0

workflows:
  sample:
    jobs:
      - cypress/run:
          start: npm start

